name: SciPy India Meet-up Proposal
description: Submit a proposal for SciPy India Virtual Meet-ups. 
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        The above GitHub issue title will be used as your talk/session title. Keep it clear and concise. Example: "Talk: Optimising research pipelines with scientific machine learning".

        Thanks for taking the time to share your learnings with the SciPy India Community! We would highly recommend you go through our [guidelines](https://github.com/scipy-india/proposal-reviewing/blob/main/guidelines.md) on submitting a proposal and giving a talk, especially if it is your first time. Please note that all talks/sessions are licensed under a [Creative Commons Attribution-Non Commercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).
  - type: dropdown
    id: format
    attributes:
      label: What format do you have in mind?
      description: Choose the format that best fits your content
      options:
        - Talk (20-25 minutes + Q&A)
        - Workshop (45-60 minutes to 3-hous, hands-on)
        - Lightning talk (5-10 minutes)
        - BoF (Birds of a Feather) session (30-45 minutes, open discussion or topic exploration with the audience)
        - Panel discussion (45-60 minutes with multiple speakers discussing a specific topic, followed by audience Q&A - please specify the panelists as well)
        - Maintainers session (45-60 minutes, open discussion with maintainers of a project or many projects about a specific topic/problem)
        - Sprints (hands-on coding session to contribute to a project or library)
        - Other (please share more details in your proposal)
    validations:
      required: true    
  - type: dropdown
    id: domain
    attributes:
      label: What domain would you say your talk/session falls under?
      description: This helps us categorise and place your talk/session to the right audience.
      options:
        - Core Python
        - Computational Tools and Scientific Python Infrastructure
        - Scientific Python Applications
        - FOSS in STEAM
        - Environmental and Earth Sciences
        - Life Sciences and Biomedicine
        - Community, Education and Outreach
        - Maintainer's stories
        - Research & Academia
        - Data Science, AI/ML, Deep learning, Neural Networks
        - Security
        - Others (please specify in the description)
    validations:
      required: true    
  - type: textarea
    id: Abstract
    attributes:
      label: Abstract
      description: Brief description about your talk/session in 40-50 words.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of what you will be talking about in 300-400 words.
    validations:
      required: true
  - type: textarea
    id: takeaways
    attributes:
      label: Key Takeaways
      description: What will the audience learn from this talk/session? What will they be able to do after this talk/session? What's the message you want to convey? (Preferably in bullet points)
    validations:
      required: true
  - type: textarea
    id: prerequisites
    attributes:
      label: Pre-requisites/Intended audience & reading material
      description: Who is this talk for? Anything that audience should read before the session starts?
  - type: textarea
    id: Resources
    attributes:
      label: Resources
      description: Any relevant resources for the reviewer(s) or the audience
  - type: input
    id: time
    attributes:
      label: Time required for the talk/session
      description: Please specify how much time does your talk/session requires (including QnA and discussion time).
    validations:
      required: true
  - type: textarea
    id: about-author
    attributes:
      label: About the Author
      description: Briefly describe who you are and what you do, especially describe your experience in the light of your proposed talk/session. Include your socials like LinkedIn, Bluesky.
    validations:
      required: true
  - type: input
    id: availability
    attributes:
      label: Availability
      description: When would you be available to give this talk/session? You may provide a specific date or a range of dates. Please also include your timezone (especially if it is not IST) or the hours of day you’re available. This will help us accommodate your session more effectively in the schedule. Note that community calls are usually held on Saturdays.
    validations:
      required: true
  - type: textarea
    id: one-line-post
    attributes:
      label: Talk/session as a Bluesky post (300 characters max)
      description: Please provide a one-line description of your talk/session that can be used as a post on Bluesky.
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Any comments
      description: Any other information that you would like to share with the reviewers or any specific requirements you have for the talk/session.
    validations:
      required: false
  - type: textarea
    id: slides
    attributes:
      label: Slides link
      description: Please provide a link to your slides, draft slides, previous recording of this talk/session or a short 5-mins long demo video of yourself giving this talk (highly recommended if you are a first-time-speaker).
    validations:
      required: false
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility & special requirements
      description: Are there any accessibility needs or special technical requirements for this talk/session?
      placeholder: Specific software or hardware requirements; e.g., Cloud computing resources required for the workshop. If possible, we(SciPy India) will try to accommodate them.
    validations:
      required: false    
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply.
      options:
        - label: I am a first time speaker (We're here to help!)
        - label: This talk/session has been delivered before
        - label: I consent to recording this talk/session and publishing it on YouTube/other platforms
        - label: I consent to using my picture (or preferred visual) and name on social media
        - label: I have read, understood, and have/will be following the [guidelines](https://github.com/scipy-india/proposal-reviewing/blob/main/guidelines.md) and [SciPy India's CoC](https://github.com/scipy-india/.github/blob/main/CODE_OF_CONDUCT.md) (must tick this one)
          required: true
  - type: markdown
    attributes:
      value: |
        ## What happens next?
        1. **Review process**: Our team will review your proposal as soon as possible.
        2. **Feedback**: We may reach out for clarifications or suggestions
        3. **Confirmation**: Once accepted, we'll coordinate the event logistics with you
        4. **Support**: First-time speakers can seek mentorship and practice sessions, if needed. Just let us know!
        **Questions?** Reach out to us:
        - 💬 [Zulip chat community](https://scipyindia.zulipchat.com/join/4mesdxfbbpl4titgtdzx4iwv/)
        - 💬 [GitHub Discussion forum](https://github.com/orgs/SciPy-India/discussions)
        - or write to us below this proposal! :)
        ---
        **Improve this questionnaire:** Did you find a bug, or do you have suggestions? Please feel free to add them to the comments above or [open a separate issue](https://github.com/scipy-india/proposal-reviewing/issues/new?template=BLANK_ISSUE) as you prefer. We welcome contributions to improve this proposal form and the overall process!
        Thank you for contributing to the SciPy India community!
        *This proposal form was inspired by and enhanced with ideas from [PyDelhi](https://github.com/pydelhi/talks). Thank you to the PyDelhi community for sharing best practices!*
